services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - flutter-deps:/root/.pub-cache
    environment:
      - FLUTTER_WEB_PORT=8080
      - FLUTTER_WEB_HOSTNAME=0.0.0.0

volumes:
  flutter-deps: 