name: urcs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  csv: ^5.1.1
  excel: ^2.1.0
  intl: ^0.18.1
  logging: ^1.2.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  pdf: ^3.10.7
  provider: ^6.1.1
  fl_chart: ^0.66.2
  logger: ^2.0.2+1
  data_table_2: ^2.5.11
  printing: ^5.11.1
  file_saver: ^0.2.12
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
